[project]
name = "scraping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crawl4ai>=0.5.0.post8",
    "dotenv>=0.9.9",
    "openai>=1.75.0",
    "requests>=2.32.3",
]
